# Generated by Django 6.0.1 on 2026-02-05 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='inn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Подтверждён'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kpp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='legal_address',
            field=models.TextField(blank=True, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mailing_address',
            field=models.TextField(blank=True, null=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название организации'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email адрес'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(unique=True, verbose_name='Уникальный код')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expiration', models.DateTimeField(verbose_name='Срок действия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Верификация email',
                'verbose_name_plural': 'Верификации email',
            },
        ),
    ]
