# Generated by Django 6.0.1 on 2026-02-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_customuser_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='Код подтверждения'),
        ),
    ]
