# Generated by Django 6.0.1 on 2026-02-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_emailverification_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='kpp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='legal_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registration_date',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
