# Generated by Django 6.0.1 on 2026-02-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeestatus',
            name='last_ping',
        ),
    ]
